CREATE TABLE Links
(
	ID int IDENTITY PRIMARY KEY,
	Link varchar(max)
)

CREATE TABLE Words
(
	ID int IDENTITY PRIMARY KEY,
	Word varchar(max)
)

CREATE TABLE WordsLinks
(
	ID INT IDENTITY PRIMARY KEY,
	LinkID INT NOT NULL FOREIGN KEY REFERENCES Links (ID),
	WordID INT NOT NULL FOREIGN KEY REFERENCES Words (ID),
	Count INT NOT NULL
)

CREATE TABLE WordsLinksPositions 
(
	ID INT IDENTITY PRIMARY KEY,
	Position INT NOT NULL
)